### ISSUE TITLE
Orgasm during kissing

### ISSUE THREAD

**Issue by elementybt** [via5/Cue#1] opened 2022-08-28 19:52 UTC
If two people are kissing when they reach 100 excitement then it does not play the climax animation. It also keeps playing the kissing sound rather than the VAMMoan orgasm sound, which I think should be prioritized over it.

(This plugin is fantastic, btw. Thank you very much for all the time you put into it.)

**Comment by via5** [comment] 2022-08-28 20:04
I can reproduce the sound issue, but the orgasm animation seems to be playing fine here.

One thing I'm noticing though is that some events will prevent parts of the orgasm animation from running because body parts are considered locked. If the hand event is running, for example, the hips won't be animated. Could this be what you're seeing?

**Comment by elementybt** [comment] 2022-08-28 20:40
Yes, I think you're correct.

**Comment by elementybt** [comment] 2022-08-28 21:16
I can open another issue as well if you'd like, but if "Mute possessed atom" is checked it does not actually unmute them when you unpossess them.

**Comment by via5** [comment] 2022-08-28 21:30
I'd rather you open a different issue. Feel free to open as many as you need, I'll check them out. You're the first one to actually use the tracker on github.

**Comment by elementybt** [comment] 2022-08-28 21:34
Would you also accept simple feature requests?

**Comment by via5** [comment] 2022-08-28 22:13
Sure.

**Comment by via5** [comment] 2022-10-19 17:31
Fixed in f5fa4244005b71cdc5bbcaea7b2e3faf4e3e10dc.

**Closed as completed by via5** 2022-10-19 17:31 UTC
Labels: bug
